#!/bin/sh
#
# This is the hook which runs when make-kpkg is invoked to create the
# flavour-dependent kernel-headers packages.
#
set -e

version=$kernver-$abiver

rm_ln ()
{
	_tdir=$1
	_dirdepth=$2

	while [ ${#} -ge 3 ]; do
		_file=${3#./*}
		rm -r $_file
		ln -s --target-directory=${_tdir} ${_dirdepth}/linux-headers-$version/$_file
		shift
	done
}

# Replace flavour-independent makefiles with symlinks to the generic
# linux-headers package.
rm_ln . .. Makefile \
    $(set -e; find . -mindepth 1 -maxdepth 1 \
	! -type d \
	-o -path './include' -o -path './scripts' \
	-prune -o -print)

# Replace flavour-independent headers with symlinks to the generic
# linux-headers package.
find . -mindepth 2 -maxdepth 2 \
	-path './include/asm-mips' \
	   -o -path './include/asm' \
	   -o -path './include/linux' \
	   -o -path './include/config' -prune \
	-o -path './include/*' \
	-exec rm -r '{}' \+

rm_ln include/asm-mips ../../.. \
    $(set -e; find . -mindepth 3 -maxdepth 3 \
	-path './include/asm-mips/offset.h' -prune \
	-o -path './include/asm-mips/*' -print)

rm_ln include/linux ../../.. \
    $(set -e; find . -mindepth 3 -maxdepth 3 \
	-path './include/linux/autoconf.h' \
	   -o -path './include/linux/compile.h' \
	   -o -path './include/linux/version.h' -prune \
	-o -path './include/linux/*' -print)

echo "$abiver-$flavour" > .extraversion

mkdir -p ../../../lib/modules/$version
(set -e; cd ../../../lib/modules/$version && ln -s /usr/src/linux-headers-$version build)
