/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "status.h"


int
main (int argc, char *argv[])
{
  GtkWidget *main_window;

#ifdef ENABLE_NLS
  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);


  add_pixmap_directory (PACKAGE_DATA_DIR "/pixmaps");
  add_pixmap_directory (PACKAGE_SOURCE_DIR "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  main_window = create_main_window ();

  /*
    my callbacks not called on configure_event ???
  */
  {
	  create_RxPathLabel(lookup_widget(GTK_WIDGET(main_window),"RxPathLabel"));
	  create_SNRLabel(lookup_widget(GTK_WIDGET(main_window),"SNRLabel"));
	  create_EchoNoiseLabel(lookup_widget(GTK_WIDGET(main_window),"EchoNoiseLabel"));
  }
  status_init (main_window);

  gtk_widget_show (main_window);

  gtk_main ();

  status_exit();
  return 0;
}

