extern void create_chart(GtkWidget *drawing_area);
extern void draw_chart(GtkWidget *drawing_area,GdkEventExpose *event);
extern void create_RxPathLabel(GtkWidget *label);
extern void create_SNRLabel(GtkWidget *label);
extern void create_EchoNoiseLabel(GtkWidget *label);
extern int status_init(GtkWidget *main_window);
extern void status_exit(void);
extern int start_msw(void);
extern void stop_msw(void);
extern int start_send_oam_lb(void);
extern void stop_send_oam_lb(void);
extern void oam_reset_counters(void);
