.TH "ELF2ECOFF" "8" "06 December 2001" "" ""
.SH NAME
elf2ecoff \- convert ELF binary to ECOFF binary
.SH SYNOPSIS

\fBelf2ecoff\fR \fIelf-executable\fR \fIecoff-executable\fR.

.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBelf2ecoff\fR command
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
\fBelf2ecoff\fR is used on the Linux/MIPS architecture to convert
an ELF kernel into an ECOFF image.
.SH "AUTHOR"
.PP
This manual page was written by Guido Guenther <agx@debian.org> for
the Debian GNU/Linux system (but may be used by others).  Permission is
granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2.
