#!/bin/sh
set -e
case "$1" in
  configure)
    adduser --quiet --system --no-create-home --force-badname \
            --group Debian-ipw3945d
    chown Debian-ipw3945d:Debian-ipw3945d /var/run/ipw3945d
    chown Debian-ipw3945d:Debian-ipw3945d /var/log/ipw3945d
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "${0} called with unknown argument ${1}"
    exit 1
    ;;
esac
#DEBHELPER#
