#!/bin/sh
#
# This is the hook which runs when make-kpkg is invoked to create the
# kernel-image packages.
#
set -e

version=$kernver-$abiver-$flavour

#
# Check whether we should force any modules to be available
# on the initrd.
#
#cd ${IMAGE_TOP}/lib/modules/${version}
#modules='@initrd_modules@'
#if [ -n "${modules}" ]; then
#  mkdir initrd
#  for i in ${modules}; do
#    if [ -f "${i}" ]; then
#      ln "${i}" initrd
#    fi
#  done
#fi

# Execute any extra post-install command provided by the arch/subarch/flavour
#if [ '@extra_postinstall_command@' ]; then
#  @extra_postinstall_command@
#fi

#
# Clean up the source symlink
#
if [ -L lib/modules/$version/source ]; then
  rm -f lib/modules/$version/source
fi
