#!/bin/sh

set -e

kbpkg=@kbpkg@

cd $DEBIAN_SRCTOP
find . -type f -path './scripts/*' ! -name '*.o' | \
	cpio -pd --preserve-modification-time $OLDPWD
cd - > /dev/null

remove=
cd include
for i in asm-*; do
	case ${i#asm-} in
	generic | $DEB_HOST_ARCH)
		;;
	*)
		remove="$remove $i"
		;;
	esac
done
${remove:+rm -r $remove}
