.\" Man page for mkinitrd.conf
.\"
.\" Copyright (C) 2001-2002 Herbert Xu <herbert@debian.org>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.\" $Id: mkinitrd.conf.5,v 1.14 2004/04/01 09:34:39 herbert Exp $
.TH MKINITRD.CONF 5 "$Date: 2004/04/01 09:34:39 $" "Initrd Tools"

.SH NAME
mkinitrd.conf \- configuration file for mkinitrd

.SH DESCRIPTION
The behaviour of
.BR mkinitrd (8)
may be altered by changing this file.  This file is meant to be parsed as a
shell script thus the syntactical rules of a shell script will apply.  See
.BR sh (1)
for more details.

.SH VARIABLES

.TP
.B MODULES
The legal values are
.IR all ,
.IR most ,
.I dep
and
.IR none .
All modules are included on the image if it is set to
.IR all .
Setting it to
.I most
will cause
.BR mkinitrd (8)
to exclude modules which are considered unlikely to be necessary in the
process of bringing up a root file system.  Setting it to
.I dep
will cause
.BR mkinitrd (8)
to use
.BR modprobe (8)
to calculate exactly what modules are needed.
Setting it to
.I none
will cause
.BR mkinitrd (8)
to not include any modules, even if modules were specified in
.IR /etc/mkinitrd/modules .

.TP
.B DELAY
The number of seconds the
.B linuxrc
script should wait to allow the user to interrupt it before the system is
brought up.

.TP
.B ROOT
If this is set to
.IR probe ,
.BR mkinitrd (8)
will try to determine the modules needed to bring up the root file system using
.IR /etc/fstab .
It will also insert code onto the image in order to setup a software
.B RAID
device if necessary.  This can be disabled by setting it to a null string.
If you get the error
.RI `` "Unknown root device" ''
then this setting must be disabled and you will need to set up the
.B initrd
image manually.

If you wish to use an alternative root device, you can specify it here and
.BR mkinitrd (8)
will use that to figure out what is needed.
You can also set the file system type of your root device by appending it
to the value of
.B ROOT
with a space in between.  You will need to quote the entire value as
otherwise the shell will interpret the file system type as a command.

This variable replaces the obsolete
.B PROBE
variable.  The values
.I probe
and the null string correspond to the values
.I on
and
.I off
for
.BR PROBE .

.TP
.B UMASK
The umask is used during the construction of the directory structure and the
final image.

.TP
.B MKIMAGE
This should be a command that produces an
.B initrd
image given a directory.  It must contain two occurrences of
.IR %s .
The first one will be replaced by the path to the directory for the candidate
image.  The other one will be replaced by the name of the output file.  This
can be used to produce images of types other than
.BR CRAMFS .
For example, to generate
.B ROMFS
images, set
.B MKIMAGE
to
.IR "'genromfs -d %s -f %s'" .

.TP
.B BUSYBOX
If this is set to
.I yes
then
.BR busybox (1)
will be included on the
.B initrd
image.

.TP
.B PKGSCRIPTS
If this is set to
.I yes
then the scripts under
.I /usr/share/initrd-tools/scripts
will be run when the
.B initrd
image is made.

.TP
.B INITRD_LD_LIBRARY_PATH
This value will be assigned to
.B LD_LIBRARY_PATH
when
.B mkinitrd
determines the library dependencies of binaries that will be copied onto
the image.

.TP
.B RESUME
If this is set, default to this partition to use for resuming.  The resume=
passed on the command line will override this setting.
The kernel needs to have the power management (PM) config's enabled.

.SH SEE ALSO
.BR mkinitrd (8)

.SH AUTHOR
Herbert Xu <herbert@debian.org>
