.\" Hey, Emacs! This is an -*- nroff -*- source file.
.\" Copyright (c) 1997 Manoj Srivastava <srivasta@debian.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139,
.\" USA.
.\"
.\"
.\"    $Id: kernel-packageconfig.es.8,v 1.3 2003/08/08 19:13:57 srivasta Exp $
.\"

.\" (c) 2003 Software in the Public Interest
.\" Esta traducción ha sido realizada por Rubén Porras <nahoo@inicia.es>
.\" Está basada en la página de manual original:
.\" versión 1.2 del CVS de
.\" /cvs/debian-doc/manpages/english/kernel-package/kernel-packageconfig.8
.\" Revisada por Rudy Godoy <rudy@kernel-panik.org>

.TH KERNEL\-PACKAGECONFIG 8 "7 de junio de 1997" "Debian" "manual Debian GNU/Linux"
.SH NOMBRE
kernel\-packageconfig \- Manejador interno del fichero /etc/kernel\-pkg.conf.
.SH SINOPSIS
.B kernel\-packageconfig
.SH DESCRIPCIÓN
La utilidad
.B kernel\-packageconfig
es usada internamente por el script de
.B postinst
de
.B kernel\-package
para preparar el fichero /etc/kernel\-pkg.conf.
Es idempotente, y sólo modifica el fichero en caso de que contenga los valores
predeterminados.
.B No
es para uso general.
.SH OPCIONES
Esta utilidad no tiene opciones.
.SH FICHEROS
El fichero afectado por este programa es
.I /etc/kernel\-pkg.conf.
.SH "VÉASE TAMBIÉN"
.B kernel\-pkg.conf (5)
.SH AUTOR
Esta página del manual fue escrita por Manoj Srivastava <srivasta@debian.org>,
para el sistema Debian GNU/Linux.
.SH TRADUCTOR
Traducción de Rubén Porras Campo <debian\-l10n\-spanish@lists.debian.org>
