#!/bin/sh

set -e

cd $DEBIAN_SRCTOP
{ 
  find . -type f -path './scripts/*' -a ! -name '*.o'
  echo "./arch/sparc/Makefile" 
} | cpio -pd --preserve-modification-time $OLDPWD
cd - > /dev/null

remove=
cd include
for i in asm-*; do
	case ${i#asm-} in
		generic | sparc | sparc64) ;;
		*) remove="$remove $i" ;;
	esac
done
${remove:+rm -r $remove}
